/* DO NOT EDIT THIS FILE */

MODEL_TYPE: PSYS

#define PI        3.1415926535897932   /* definition of PI                        */
#define TWOPI     6.2831853071795862   /* definition of 2.0*PI                    */
#define E         2.71828182845904524  /* definition of E                         */
#define EINV      0.36787944117144232  /* definition of E Inverse (1/E)           */
#define RT2       1.4142135623730952   /* definition of square root 2.0           */
#define RT3       1.7320508075688773   /* definition of square root 3.0           */

#define INV_ROOT2 0.707106781                                                       
#define a1re      -0.5                 /* a operator constants                    */
#define a1im      0.866025403                                                       
#define a2re      -0.5                 /* a2 operator constants                   */
#define a2im      -0.866025403                                                      

INPUTS:
  double i1;
  double i2;
  double i3;

OUTPUTS:
  int quenched;

NODES:
  double N1;
  double N2;
  double IN2;
  double IN3;
  double OUT2;
  double OUT3;

PARAMETERS:
  double Ta;
  char   Name[11];

GVALUES:
  double GRVAL;
  double GRVAL2;
  double GRVAL3;

INPUTS:
  int reset  = createInput( strcat2("Reset",Name), "TRUE");
  int enable = createInput( strcat2("En",Name),    "TRUE");

OUTPUTS:
  double R1     = createOutput( strcat2(Name," phA R"), strcat2("SFCL resistance|",Name),  -10, 110, "ohm", "TRUE");
  double R2     = createOutput( strcat2(Name," phB R"), strcat2("SFCL resistance|",Name),  -10, 110, "ohm", "TRUE");
  double R3     = createOutput( strcat2(Name," phC R"), strcat2("SFCL resistance|",Name),  -10, 110, "ohm", "TRUE");
  double T1     = createOutput( strcat2(Name," phA T"), strcat2("SFCL Temperature|",Name), -10, 110, "K",   "TRUE");
  double T2     = createOutput( strcat2(Name," phB T"), strcat2("SFCL Temperature|",Name), -10, 110, "K",   "TRUE");
  double T3     = createOutput( strcat2(Name," phC T"), strcat2("SFCL Temperature|",Name), -10, 110, "K",   "TRUE");
  int    state1 = createOutput( strcat2(Name," phA S"), strcat2("SFCL State|",Name),       -10, 110, " ",   "TRUE");
  int    state2 = createOutput( strcat2(Name," phB S"), strcat2("SFCL State|",Name),       -10, 110, " ",   "TRUE");
  int    state3 = createOutput( strcat2(Name," phC S"), strcat2("SFCL State|",Name),       -10, 110, " ",   "TRUE");

